name: Deploy

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-web-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build a container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            registry.digitalocean.com/postanu/web:${{ github.sha }}
            registry.digitalocean.com/postanu/web:latest
          cache-from: type=local,src=/tmp/.buildx-web-cache
          cache-to: type=local,dest=/tmp/.buildx-web-cache-new,mode=max

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-web-cache
          mv /tmp/.buildx-web-cache-new /tmp/.buildx-web-cache

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: postanu-stage
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '
            [
              {
                "name": "web",
                "image": {
                  "registry_type": "DOCR",
                  "repository": "web",
                  "tag": "${{ github.sha }}"
                }
              }
            ]'
